### Caso 1: Registro Exitoso (201 Created)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "usuario": "prueba_ucab",
    "email": "prueba@ucab.edu.ve",
    "contrasena": "Password123",
    "confirmarContrasena": "Password123",
    "cedula": "V-12345678",
    "nombre": "Estudiante",
    "apellido": "UCAB",
    "tipoPersona": "UCAB",
    "direccion": "La Castellana",
    "telefono": "0412-1234567"
}

### Caso 2: Email invalido (201 Created)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "usuario": "prueba_ucab",
    "email": "prueba@hotma.ve",
    "contrasena": "Password123",
    "confirmarContrasena": "Password123",
    "cedula": "V-12345678",
    "nombre": "Estudiante",
    "apellido": "UCAB",
    "tipoPersona": "UCAB",
    "direccion": "La Castellana",
    "telefono": "0412-1234567"
}


### Caso 3: Contraseña Invalida (201 Created)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "usuario": "prueba_ucab",
    "email": "prueba@hotmail.ve",
    "contrasena": "Password3",
    "confirmarContrasena": "Password123",
    "cedula": "V-12345678",
    "nombre": "Estudiante",
    "apellido": "UCAB",
    "tipoPersona": "UCAB",
    "direccion": "La Castellana",
    "telefono": "0412-1234567"
}


### Caso 4: Email invalido (201 Created)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "usuario": "prueba_ucab",
    "email": "prueba@est.ucab.edu.ve",
    "contrasena": "Password123",
    "confirmarContrasena": "Password123",
    "cedula": "V-12345678",
    "nombre": "Estudiante",
    "apellido": "UCAB",
    "tipoPersona": "VISITANTE",
    "direccion": "La Castellana",
    "telefono": "0412-1234567"
}

### Caso 4: Telefono Invalido (201 Created)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "usuario": "prueba_ucab",
    "email": "prueba@est.ucab.edu.ve",
    "contrasena": "Password123",
    "confirmarContrasena": "Password123",
    "cedula": "V-12345678",
    "nombre": "Estudiante",
    "apellido": "UCAB",
    "tipoPersona": "UCAB",
    "direccion": "La Castellana",
    "telefono": "04121234567"
}

### Caso 4: Encontrado en la base de datos (201 Created)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "usuario": "prueba_ucab",
    "email": "prueba@est.ucab.edu.ve",
    "contrasena": "Password123",
    "confirmarContrasena": "Password123",
    "cedula": "V-12345678",
    "nombre": "Estudiante",
    "apellido": "UCAB",
    "tipoPersona": "UCAB",
    "direccion": "La Castellana",
    "telefono": "0412-1234567"
}

### Caso 5: Formato de Cédula Inválido (400 Bad Request)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "usuario": "prueba_ucab_invalida",
    "email": "nuevo@test.com",
    "contrasena": "Password123",
    "confirmarContrasena": "Password123",
    "cedula": "12345", 
    "nombre": "Estudiante",
    "apellido": "UCAB",
    "tipoPersona": "UCAB",
    "direccion": "La Castellana",
    "telefono": "0412-1234567"
}